### ISSUE TITLE
Small mistake in vnachannel.py

### ISSUE THREAD

**Issue by KevinNadaud** [Terrabits/rohdeschwarz#1]
Thank you very much for the python scripting for controlling VNA, its works perfectly well. Nevertheless, there are a small mistake in the file vnachannel.py

line 26, it should be 
    `db_degrees = 'LOGP'`
instead of
   ` db_degress = 'LOGP'`

Regards

**Comment by Terrabits** [comment]
Glad you're finding use for it :-) and thanks for finding and opening the issue.
I've fixed the misspelling and uploaded a new version of the source code and PyPi package.

I think I can close this...?

**Comment by KevinNadaud** [comment]
Yes, if it fixed, you can close this !

Regards

**Comment by Terrabits** [comment]
It is fixed :-)
